services:
  pg:
    image: bitnami/postgresql:latest
    container_name: focus-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=focus
    volumes:
      - ./docker-data:/bitnami/postgresql
